site_name: PowERP Docs
repo_name: GitHub
repo_url: https://github.com/gisce/powerp-docs
edit_uri: edit/master/docs
site_author: GISCE-TI, S.L.
google_analytics: ['UA-27668469-4', 'builds.gisce.net']
theme: readthedocs

markdown_extensions:
  - admonition
  - grid_tables
  - markdown_blockdiag:
      fontpath: fonts/DejaVuSans.ttf

pages:
  - Home: index.md
  - Base:
    - Partners: base/partners.md
    - PowerEmail: base/poweremail.md
    - Gestió ATR: base/atr.md
    - Atenció al Client: base/atc.md
    - Gestió de polisses: base/polisses.md
    - Gestió de comptadors: base/comptadors.md
  - Distribuidora:
    - Inicio: distri/index.md
    - Telegestió: distri/telegestion.md
    - Contadors: distri/contadores.md
    - Manual d'ús de TPL: distri/tpl.md
    - Manual d'ús de TPL:
      - Requeriments del sistema i instal·lació: distri/tpl/requeriments.md
      - Procés de treball: distri/tpl/proces_de_treball.md
      - Descàrrega electrònica de Tancaments i Curves: distri/tpl/decarrega_tancaments_i_curves.md
      - Fitxers d'intercanvi per GISCE-TPL: distri/tpl/intercanvi_tpl.md
      - Fitxers d'intercanvi entre GISCE-TPL i GISCE-ERP: distri/tpl/intercanvi_tpl_erp.md
    - CUPS: distri/cups.md
    - Pòlisses: distri/polizas.md
    - Facturació: distri/facturacion.md
    - Facturació:
      - Peatges: distri/facturacion_peajes.md
      - Règim especial: distri/facturacio_re.md
      - Liquidació: distri/liquidacion_peajes.md
      - Contractació: distri/facturacion_contratacion.md
    - Administració Pública:
      - REE: distri/adm-pub/ree.md
      - CNMC: distri/adm-pub/cnmc.md
      - AEAT: distri/adm-pub/aeat.md
      - Gencat: distri/adm-pub/gencat.md
    - Perfils: distri/perfiles.md
    - Descarrecs: distri/descarrecs.md
    - GIS:
      - GIS Web:
        - Visor web: gis/webgis.md
        - Buscador: gis/websearch.md
      - Qgis: gis/qgis.md
      - Instalacions:
        - Subestacions: distri/subestaciones.md
        - CTS: distri/cts.md
        - CTS:
          - Cel·les i elements de tall: distri/celles.md
        - LAT: distri/lat.md
        - LBT: distri/lbt.md
        - Instalacions RE: distri/re.md
        - Expedients: distri/expedientes.md
        - Despatxos: distri/despatxos.md
        - Sincronització CUPS: distri/sincronizacion_cups.md
        - CINI - Generació Automàtica: distri/act_cinis.md
        - TI - Generació Automàtica: distri/act_tis.md
    - Qualitat de servei: distri/qualitat.md
    - Qualitat de servei:
      - Termes i Definicions: distri/qualitat/termes_i_def.md
      - Marc de referència del model de qualitat: distri/qualitat/marc_ref_model.md
      - Model de qualitat per la qualitat interna i externa: distri/qualitat/model_interna_i_externa.md
      - Model de qualitat per la qualitat en us: distri/qualitat/model_en_us.md
      - Generació d'incidències: distri/qualitat/generacio_incidencies.md
      - Obtenció de resultats: distri/qualitat/obtencio_resultats.md
    - Qualitat individual: distri/qualitat_individual.md
  - Comercialitzadora:
    - Inici: comer/index.md
    - CUPS: comer/cups.md
    - Contractes: comer/contratos.md
    - Facturació: comer/facturacion.md
    - Gestió ATR: comer/atr.md
    - SIPS: comer/sips.md
    - Administració Pública:
      - CNMC: comer/adm-pub/cnmc.md
      - AEAT: comer/adm-pub/aeat.md
      - Gencat: comer/adm-pub/gencat.md
      - Informes: comer/adm-pub/informes.md
      - Tases Municipals: comer/adm-pub/municipal_taxes.md
  - Facturació:
    - Validacions: facturacio/validacions.md
    - Gestió de canvi d'any: facturacio/canvi_any.md
    - Gestió de pagaments i cobraments: facturacio/cobraments.md
    - Gestió de lectures: facturacio/lectures.md
    - Lots: facturacio/lots.md
